name: douban movie sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_MOVIE_URL: ${{ secrets.NOTION_MOVIE_URL }}
        NOTION_BOOK_URL: ${{ secrets.NOTION_BOOK_URL }}
        DOUBAN_NAME: ${{ secrets.DOUBAN_NAME }}
        YEAR: ${{ vars.YEAR }}
        REF: ${{ github.ref }}
        REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: douban movie sync
        run: |
          python -u scripts/douban.py "movie"
      - name: Remove folder
        run: rm -rf ./OUT_FOLDER
      - name: Set default year if not provided
        run: echo "YEAR=$(date +"%Y")" >> $GITHUB_ENV
        if: env.YEAR == ''
      - name: push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'add new heatmap' || echo "nothing to commit"
          git push || echo "nothing to push"
